<?php
	/**
	 * ☺ Amity Framework
	 * © Copyright Alexis Jehan
	 */
	/**
	 * Template de la page principale
	 * 
	 * Ce template définit le contenu de la page principale du site.
	 * 
	 * @package    application
	 * @subpackage templates
	 * @author     Alexis Jehan <alexis.jehan2@gmail.com>
	 * @version    20/07/2015
	 * @since      01/08/2014
	 */
?>
			<div class="icon" alt="<?php echo __NAME__; ?>" title="<?php echo __NAME__; ?>"></div>
			<div>
				<p>Thank you for <i>downloading</i> !</p>
				<p>This looks like the beginning of a beautiful <b>amity</b>... &#9786;</p>
				<hr/>
				<i>(You can change this default content in the template folder)</i>
			</div>
