<?php
	/*
	 * MIT License
	 *
	 * Copyright (c) 2017-2023 Alexis Jehan
	 *
	 * Permission is hereby granted, free of charge, to any person obtaining a copy
	 * of this software and associated documentation files (the "Software"), to deal
	 * in the Software without restriction, including without limitation the rights
	 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	 * copies of the Software, and to permit persons to whom the Software is
	 * furnished to do so, subject to the following conditions:
	 *
	 * The above copyright notice and this permission notice shall be included in all
	 * copies or substantial portions of the Software.
	 *
	 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	 * SOFTWARE.
	 */

	/**
	 * Template de la page principale (en français)
	 * 
	 * Ce template définit le contenu de la page principale du site en français.
	 * 
	 * @package    application
	 * @subpackage templates
	 * @author     Alexis Jehan <alexis.jehan2@gmail.com>
	 * @version    05/08/2015
	 * @since      01/08/2014
	 */
?>
			<div class="icon" alt="<?php echo __NAME__; ?>" title="<?php echo __NAME__; ?>"></div>
			<div>
				<p>Merci pour le <i>téléchargement</i> !</p>
				<p>Ça sent comme le début d'une grande <b>amitié</b>... &#9786;</p>
				<hr/>
				<i>(Vous pouvez changer ce contenu dans le dossier des templates)</i>
			</div>
