<?php
	/**
	 * ☺ Amity Framework
	 * © Copyright Alexis Jehan
	 */
	/**
	 * Template de la page principale (en français)
	 * 
	 * Ce template définit le contenu de la page principale du site en français.
	 * 
	 * @package    application
	 * @subpackage templates
	 * @author     Alexis Jehan <alexis.jehan2@gmail.com>
	 * @version    05/08/2015
	 * @since      01/08/2014
	 */
?>
<div class="icon" alt="<?php echo __NAME__; ?>" title="<?php echo __NAME__; ?>"></div>
<div>
	<p>Merci pour le <i>téléchargement</i> !</p>
	<p>Ça sent comme le début d'une grande <b>amitié</b>... &#9786;</p>
	<hr />
	<i>(Vous pouvez changer ce contenu dans le dossier des templates)</i>
</div>