<?php
	/*
	 * MIT License
	 *
	 * Copyright (c) 2017-2023 Alexis Jehan
	 *
	 * Permission is hereby granted, free of charge, to any person obtaining a copy
	 * of this software and associated documentation files (the "Software"), to deal
	 * in the Software without restriction, including without limitation the rights
	 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	 * copies of the Software, and to permit persons to whom the Software is
	 * furnished to do so, subject to the following conditions:
	 *
	 * The above copyright notice and this permission notice shall be included in all
	 * copies or substantial portions of the Software.
	 *
	 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	 * SOFTWARE.
	 */

	/**
	 * Template squelette et principal du site
	 * 
	 * Ce template encadre chaque page du site et définit donc la structure générale de chacune d'elles, il est aussi utilisé lors du rendu de n'importe quel contrôleur.
	 * 
	 * @package    application
	 * @subpackage templates
	 * @author     Alexis Jehan <alexis.jehan2@gmail.com>
	 * @version    20/07/2015
	 * @since      01/08/2014
	 */
?>
<!doctype html>
<html lang="<?php echo $language; ?>">
	<head>
		<meta charset="utf-8"/>
		<meta name="generator" content="<?php echo __NAME__ . ' ' . __VERSION__; ?>"/>
		<link rel="icon" type="image/png" href="<?php echo ASSETS_URL; ?>/images/logo-amity.png"/>
		<link rel="stylesheet" href="<?php echo ASSETS_URL; ?>/css/stylesheet.css"/>
		<title><?php echo 'home' !== $controller ? $title . ' &ndash; ' . APP_NAME : APP_NAME; ?></title>
	</head>
	<body>
		<header>
			<h1><?php echo $title; ?></h1>
		</header>
		<main>
<?php
	echo $content;
?>
		</main>
		<footer>
<?php
	if (DEV_MODE):
?>
			<small><?php echo __('Page generated in %s seconds.', '<b>' . chrono() . '</b>'); ?></small>
<?php
	endif;
?>
		</footer>
		<script src="<?php echo ASSETS_URL; ?>/js/script.js"></script>
	</body>
</html>